### ISSUE TITLE
List not populating for Content Editor

### ISSUE THREAD

**Issue by Kilvoctu** [snipercup/CDDA-Content-Manager#37]
It appears that ever since release 0.5.3, the content editor's type list isn't populating. This issue has persisted up to the current version 0.5.7. Last known working version is 0.5.3.

Cataclysm game folder is set to my CDDA's root folder, where cataclysm-tiles.exe is located.
All the other functions are working as expected.

I opened developer tools via ctrl+shift+i, but not sure what I should be looking for. The console doesn't show any errors. 

![Untitled](https://user-images.githubusercontent.com/2993060/74292167-f12dc680-4cfc-11ea-9b0b-4779c36755e7.png)

**Comment by snipercup** [comment]
Thanks for reporting. I already made a new release with the bugfix https://github.com/snipercup/CDDA-Content-Manager/releases/tag/0.5.8
