### ISSUE TITLE
Awesome Work! Perhaps Adding A "Save To New File" Option?

### ISSUE THREAD

**Issue by DrPariah** [snipercup/CDDA-Content-Manager#49]
Hey there, sorry to bother you! This is a very cool program. I was scrounging the Internet to see if someone had made some tools for CDDA, and, well, here we are. There was a recent thread [https://discourse.cataclysmdda.org/t/game-features-for-player-created-content/24091] on the CDDA Discourse about potentially making dev tools or optional self-generated player starting quests, and this thing would help out modding tremendously if it was possible to save the output to a new file within the program. Basically, make a new blank JSON file to save your copies to. Possibly allow creation of a Mod Info JSON in the same method, so that way you could make a mod without having to leave the tool - just save your output in a folder, copy to CDDA Mods, and you're done. Would this be possible? Could it be done by integrating with NotePad++ to outsource some of those functions?
(Also I noted that not all flags are available on items - things like SEMITANGIBLE are not present, for instance. Dunno if this is based on when the tool was first made or what.)

**Comment by snipercup** [comment]
Thank you for your interest. I added a save as button, you can try out the newest release: https://github.com/snipercup/CDDA-Content-Manager/releases/tag/0.6.6 please read the description of the release.

If you wanted to create a new modinfo file you would open the content editor and select type:modinfo. Then click save as and navigate to the folder of your new mod (you have to create the folder first if it does not exist) in \data\mods and click save. Then you need to reload the content manager to have your new entry show up in the list. The same can be done for other types.

As for the missions, I think there needs to be a specialized tool to effectively create missions, perhaps similar to the dialog editor. You can select type: mission_definition  in the content editor right now but I think the schema is not completed yet for that type so it probably won't work very well.

As for the flag, the content editor is behind on the developement of CDDA it seems. I saw that the flags have been jsonized so i'd like to change the schema's to accomodate that. That way new flags will properly load in the future.

**Comment by DrPariah** [comment]
Thank you! I'll try it out!
I'd definitely agree with you regarding a specialized tool for Missions. The dream setup would be to have a map and building editor that would link into it - that way, you could use it not just for Missions (which can change terrain, as an example the initial clear out the zombies mission in the Refugee Center opens a set of shutters after you've completed it) but you could also adapt it for Faction Camps. But that's pie in the sky stuff. The simple idea of having a dedicated Missions tool would take a ton of work off .

**Comment by snipercup** [comment]
The button has been added albeit not perfect
